### ISSUE TITLE
Name Error in MakeSet..py

### ISSUE THREAD

**Issue by RishabhDarmwal** [bannyvishwas2020/MyHandWriting#15]
File "E:/MyHandWriting-version3/MakeSet.py", line 213, in <module>
    elif event.type == MOUSEBUTTONDOWN:

NameError: name 'MOUSEBUTTONDOWN' is not defined

**Comment by bannyvishwas** [comment]
Please ensure that you installed right modules and imported them 
specifically :  "from pygame.locals import *"
