### ISSUE TITLE
Need character sets in version 

### ISSUE THREAD

**Issue by zahash** [bannyvishwas2020/MyHandWriting#16]
Can you please upload more character sets in version 3 so that we can use the software without having to create our own.

**Comment by bannyvishwas** [comment]
It will be best to create your own letter set once and use anytime. If I do so, than handwriting will be in my style only then there will be a difference in handwriting. I will put a sample handwriting although.

**Comment by zahash** [comment]
The problem with creating my own handwriting is that I will have to do it with my mouse. I don't have a digital pad.
I'm horrible at writing alphabets with my mouse.

**Comment by bannyvishwas** [comment]
ok dude.. I will add a sample handwriting set including all symbols and letters.
